/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/Albums": {
    get: {
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Album"][];
          "application/json": components["schemas"]["Album"][];
          "text/json": components["schemas"]["Album"][];
        };
      };
    };
    post: {
      requestBody: {
        "application/json-patch+json": components["schemas"]["Album"];
        "application/json": components["schemas"]["Album"];
        "text/json": components["schemas"]["Album"];
        "application/*+json": components["schemas"]["Album"];
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Album"];
          "application/json": components["schemas"]["Album"];
          "text/json": components["schemas"]["Album"];
        };
      };
    };
  };
  "/Albums/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Album"];
          "application/json": components["schemas"]["Album"];
          "text/json": components["schemas"]["Album"];
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: number;
        };
      };
      requestBody: {
        "application/json-patch+json": components["schemas"]["Album"];
        "application/json": components["schemas"]["Album"];
        "text/json": components["schemas"]["Album"];
        "application/*+json": components["schemas"]["Album"];
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
    delete: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/Articles": {
    get: {
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Article"][];
          "application/json": components["schemas"]["Article"][];
          "text/json": components["schemas"]["Article"][];
        };
      };
    };
    post: {
      requestBody: {
        "application/json-patch+json": components["schemas"]["Article"];
        "application/json": components["schemas"]["Article"];
        "text/json": components["schemas"]["Article"];
        "application/*+json": components["schemas"]["Article"];
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Article"];
          "application/json": components["schemas"]["Article"];
          "text/json": components["schemas"]["Article"];
        };
      };
    };
  };
  "/Articles/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Article"];
          "application/json": components["schemas"]["Article"];
          "text/json": components["schemas"]["Article"];
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: number;
        };
      };
      requestBody: {
        "application/json-patch+json": components["schemas"]["Article"];
        "application/json": components["schemas"]["Article"];
        "text/json": components["schemas"]["Article"];
        "application/*+json": components["schemas"]["Article"];
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
    delete: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/Emails": {
    get: {
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Email"][];
          "application/json": components["schemas"]["Email"][];
          "text/json": components["schemas"]["Email"][];
        };
      };
    };
    post: {
      requestBody: {
        "application/json-patch+json": components["schemas"]["Email"];
        "application/json": components["schemas"]["Email"];
        "text/json": components["schemas"]["Email"];
        "application/*+json": components["schemas"]["Email"];
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Email"];
          "application/json": components["schemas"]["Email"];
          "text/json": components["schemas"]["Email"];
        };
      };
    };
  };
  "/Emails/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Email"];
          "application/json": components["schemas"]["Email"];
          "text/json": components["schemas"]["Email"];
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: number;
        };
      };
      requestBody: {
        "application/json-patch+json": components["schemas"]["Email"];
        "application/json": components["schemas"]["Email"];
        "text/json": components["schemas"]["Email"];
        "application/*+json": components["schemas"]["Email"];
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
    delete: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/Media": {
    get: {
      parameters: {
        query: {
          page?: number;
          size?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Media"][];
          "application/json": components["schemas"]["Media"][];
          "text/json": components["schemas"]["Media"][];
        };
      };
    };
  };
  "/Media/Image": {
    get: {
      parameters: {
        query: {
          page?: number;
          size?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Media"][];
          "application/json": components["schemas"]["Media"][];
          "text/json": components["schemas"]["Media"][];
        };
      };
    };
  };
  "/Media/Video": {
    get: {
      parameters: {
        query: {
          page?: number;
          size?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Media"][];
          "application/json": components["schemas"]["Media"][];
          "text/json": components["schemas"]["Media"][];
        };
      };
    };
  };
  "/Media/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Media"];
          "application/json": components["schemas"]["Media"];
          "text/json": components["schemas"]["Media"];
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: number;
        };
      };
      requestBody: {
        "application/json-patch+json": components["schemas"]["Media"];
        "application/json": components["schemas"]["Media"];
        "text/json": components["schemas"]["Media"];
        "application/*+json": components["schemas"]["Media"];
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
    delete: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/Posts": {
    get: {
      parameters: {
        query: {
          page?: number;
          size?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Post"][];
          "application/json": components["schemas"]["Post"][];
          "text/json": components["schemas"]["Post"][];
        };
      };
    };
    post: {
      requestBody: {
        "application/json-patch+json": components["schemas"]["Post"];
        "application/json": components["schemas"]["Post"];
        "text/json": components["schemas"]["Post"];
        "application/*+json": components["schemas"]["Post"];
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Post"];
          "application/json": components["schemas"]["Post"];
          "text/json": components["schemas"]["Post"];
        };
      };
    };
  };
  "/Posts/Update": {
    get: {
      parameters: {
        query: {
          page?: number;
          size?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Post"][];
          "application/json": components["schemas"]["Post"][];
          "text/json": components["schemas"]["Post"][];
        };
      };
    };
  };
  "/Posts/Event": {
    get: {
      parameters: {
        query: {
          page?: number;
          size?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Post"][];
          "application/json": components["schemas"]["Post"][];
          "text/json": components["schemas"]["Post"][];
        };
      };
    };
  };
  "/Posts/History": {
    get: {
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["History"][];
          "application/json": components["schemas"]["History"][];
          "text/json": components["schemas"]["History"][];
        };
      };
    };
  };
  "/Posts/History/{year}/{month}": {
    get: {
      parameters: {
        path: {
          year: number;
          month: number;
        };
        query: {
          page?: number;
          size?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Post"][];
          "application/json": components["schemas"]["Post"][];
          "text/json": components["schemas"]["Post"][];
        };
      };
    };
  };
  "/Posts/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Post"];
          "application/json": components["schemas"]["Post"];
          "text/json": components["schemas"]["Post"];
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: number;
        };
      };
      requestBody: {
        "application/json-patch+json": components["schemas"]["Post"];
        "application/json": components["schemas"]["Post"];
        "text/json": components["schemas"]["Post"];
        "application/*+json": components["schemas"]["Post"];
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
    delete: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/Songs": {
    get: {
      parameters: {
        query: {
          page?: number;
          size?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Song"][];
          "application/json": components["schemas"]["Song"][];
          "text/json": components["schemas"]["Song"][];
        };
      };
    };
    post: {
      requestBody: {
        "application/json-patch+json": components["schemas"]["Song"];
        "application/json": components["schemas"]["Song"];
        "text/json": components["schemas"]["Song"];
        "application/*+json": components["schemas"]["Song"];
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Song"];
          "application/json": components["schemas"]["Song"];
          "text/json": components["schemas"]["Song"];
        };
      };
    };
  };
  "/Songs/Genre/{genre}": {
    get: {
      parameters: {
        path: {
          genre: string;
        };
        query: {
          page?: number;
          size?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Song"][];
          "application/json": components["schemas"]["Song"][];
          "text/json": components["schemas"]["Song"][];
        };
      };
    };
  };
  "/Songs/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Song"];
          "application/json": components["schemas"]["Song"];
          "text/json": components["schemas"]["Song"];
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: number;
        };
      };
      requestBody: {
        "application/json-patch+json": components["schemas"]["Song"];
        "application/json": components["schemas"]["Song"];
        "text/json": components["schemas"]["Song"];
        "application/*+json": components["schemas"]["Song"];
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
    delete: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/Songs/Top": {
    get: {
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["TopSong"][];
          "application/json": components["schemas"]["TopSong"][];
          "text/json": components["schemas"]["TopSong"][];
        };
      };
    };
    post: {
      requestBody: {
        "application/json-patch+json": components["schemas"]["TopSong"];
        "application/json": components["schemas"]["TopSong"];
        "text/json": components["schemas"]["TopSong"];
        "application/*+json": components["schemas"]["TopSong"];
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["TopSong"];
          "application/json": components["schemas"]["TopSong"];
          "text/json": components["schemas"]["TopSong"];
        };
      };
    };
  };
  "/Songs/Top/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["TopSong"];
          "application/json": components["schemas"]["TopSong"];
          "text/json": components["schemas"]["TopSong"];
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: number;
        };
      };
      requestBody: {
        "application/json-patch+json": components["schemas"]["TopSong"];
        "application/json": components["schemas"]["TopSong"];
        "text/json": components["schemas"]["TopSong"];
        "application/*+json": components["schemas"]["TopSong"];
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
    delete: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/Users": {
    get: {
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["User"][];
          "application/json": components["schemas"]["User"][];
          "text/json": components["schemas"]["User"][];
        };
      };
    };
    post: {
      requestBody: {
        "application/json-patch+json": components["schemas"]["User"];
        "application/json": components["schemas"]["User"];
        "text/json": components["schemas"]["User"];
        "application/*+json": components["schemas"]["User"];
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["User"];
          "application/json": components["schemas"]["User"];
          "text/json": components["schemas"]["User"];
        };
      };
    };
  };
  "/Users/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["User"];
          "application/json": components["schemas"]["User"];
          "text/json": components["schemas"]["User"];
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: number;
        };
      };
      requestBody: {
        "application/json-patch+json": components["schemas"]["User"];
        "application/json": components["schemas"]["User"];
        "text/json": components["schemas"]["User"];
        "application/*+json": components["schemas"]["User"];
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
    delete: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
}

export interface operations {}

export interface components {
  schemas: {
    TopSong: {
      created?: string;
      lastModified?: string;
      id?: number;
      rank?: number | null;
      songId?: number;
      song: components["schemas"]["Song"];
    };
    MediaType: 0 | 1;
    Post: {
      created?: string;
      lastModified?: string;
      id?: number;
      title: string;
      content?: string | null;
      link?: string | null;
      gallery?: components["schemas"]["Media"][] | null;
    };
    Media: {
      created?: string;
      lastModified?: string;
      id?: number;
      url: string;
      type: components["schemas"]["MediaType"];
      post?: components["schemas"]["Post"];
      article?: components["schemas"]["Article"];
    };
    Article: {
      created?: string;
      lastModified?: string;
      id?: number;
      title: string;
      content: string;
      song?: components["schemas"]["Song"];
      gallery?: components["schemas"]["Media"][] | null;
    };
    Song: {
      created?: string;
      lastModified?: string;
      id?: number;
      title: string;
      genre?: string | null;
      soundCloud?: string | null;
      audio?: string | null;
      album: components["schemas"]["Album"];
      topSong?: components["schemas"]["TopSong"];
      articleId?: number | null;
      article?: components["schemas"]["Article"];
    };
    Album: {
      created?: string;
      lastModified?: string;
      id?: number;
      title: string;
      genre: string;
      songs: components["schemas"]["Song"][];
      coverImage?: string | null;
    };
    User: {
      created?: string;
      lastModified?: string;
      id?: number;
      ipAddress?: string | null;
    };
    Email: {
      created?: string;
      lastModified?: string;
      id?: number;
      address: string;
      message: string;
      title?: string | null;
      template?: string | null;
      isSuccess: boolean;
      user?: components["schemas"]["User"];
    };
    History: {
      year: number;
      month: number;
      count: number;
    };
  };
}
