/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/Albums": {
    get: {
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Album"][];
          "application/json": components["schemas"]["Album"][];
          "text/json": components["schemas"]["Album"][];
        };
      };
    };
    post: {
      requestBody: {
        "application/json-patch+json": components["schemas"]["Album"];
        "application/json": components["schemas"]["Album"];
        "text/json": components["schemas"]["Album"];
        "application/*+json": components["schemas"]["Album"];
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Album"];
          "application/json": components["schemas"]["Album"];
          "text/json": components["schemas"]["Album"];
        };
      };
    };
  };
  "/Albums/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Album"];
          "application/json": components["schemas"]["Album"];
          "text/json": components["schemas"]["Album"];
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: number;
        };
      };
      requestBody: {
        "application/json-patch+json": components["schemas"]["Album"];
        "application/json": components["schemas"]["Album"];
        "text/json": components["schemas"]["Album"];
        "application/*+json": components["schemas"]["Album"];
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
    delete: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/Articles": {
    get: {
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Article"][];
          "application/json": components["schemas"]["Article"][];
          "text/json": components["schemas"]["Article"][];
        };
      };
    };
    post: {
      requestBody: {
        "application/json-patch+json": components["schemas"]["Article"];
        "application/json": components["schemas"]["Article"];
        "text/json": components["schemas"]["Article"];
        "application/*+json": components["schemas"]["Article"];
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Article"];
          "application/json": components["schemas"]["Article"];
          "text/json": components["schemas"]["Article"];
        };
      };
    };
  };
  "/Articles/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Article"];
          "application/json": components["schemas"]["Article"];
          "text/json": components["schemas"]["Article"];
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: number;
        };
      };
      requestBody: {
        "application/json-patch+json": components["schemas"]["Article"];
        "application/json": components["schemas"]["Article"];
        "text/json": components["schemas"]["Article"];
        "application/*+json": components["schemas"]["Article"];
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
    delete: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/Emails": {
    get: {
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Email"][];
          "application/json": components["schemas"]["Email"][];
          "text/json": components["schemas"]["Email"][];
        };
      };
    };
    post: {
      requestBody: {
        "application/json-patch+json": components["schemas"]["Email"];
        "application/json": components["schemas"]["Email"];
        "text/json": components["schemas"]["Email"];
        "application/*+json": components["schemas"]["Email"];
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Email"];
          "application/json": components["schemas"]["Email"];
          "text/json": components["schemas"]["Email"];
        };
      };
    };
  };
  "/Emails/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Email"];
          "application/json": components["schemas"]["Email"];
          "text/json": components["schemas"]["Email"];
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: number;
        };
      };
      requestBody: {
        "application/json-patch+json": components["schemas"]["Email"];
        "application/json": components["schemas"]["Email"];
        "text/json": components["schemas"]["Email"];
        "application/*+json": components["schemas"]["Email"];
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
    delete: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/Media": {
    get: {
      parameters: {
        query: {
          page?: number;
          size?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Media"][];
          "application/json": components["schemas"]["Media"][];
          "text/json": components["schemas"]["Media"][];
        };
      };
    };
    post: {
      requestBody: {
        "application/json-patch+json": components["schemas"]["Media"];
        "application/json": components["schemas"]["Media"];
        "text/json": components["schemas"]["Media"];
        "application/*+json": components["schemas"]["Media"];
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Media"];
          "application/json": components["schemas"]["Media"];
          "text/json": components["schemas"]["Media"];
        };
      };
    };
  };
  "/Media/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Media"];
          "application/json": components["schemas"]["Media"];
          "text/json": components["schemas"]["Media"];
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: number;
        };
      };
      requestBody: {
        "application/json-patch+json": components["schemas"]["Media"];
        "application/json": components["schemas"]["Media"];
        "text/json": components["schemas"]["Media"];
        "application/*+json": components["schemas"]["Media"];
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
    delete: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/Posts": {
    get: {
      parameters: {
        query: {
          page?: number;
          size?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Post"][];
          "application/json": components["schemas"]["Post"][];
          "text/json": components["schemas"]["Post"][];
        };
      };
    };
    post: {
      requestBody: {
        "application/json-patch+json": components["schemas"]["Post"];
        "application/json": components["schemas"]["Post"];
        "text/json": components["schemas"]["Post"];
        "application/*+json": components["schemas"]["Post"];
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Post"];
          "application/json": components["schemas"]["Post"];
          "text/json": components["schemas"]["Post"];
        };
      };
    };
  };
  "/Posts/Events": {
    get: {
      parameters: {
        query: {
          page?: number;
          size?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Post"][];
          "application/json": components["schemas"]["Post"][];
          "text/json": components["schemas"]["Post"][];
        };
      };
    };
  };
  "/Posts/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Post"];
          "application/json": components["schemas"]["Post"];
          "text/json": components["schemas"]["Post"];
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: number;
        };
      };
      requestBody: {
        "application/json-patch+json": components["schemas"]["Post"];
        "application/json": components["schemas"]["Post"];
        "text/json": components["schemas"]["Post"];
        "application/*+json": components["schemas"]["Post"];
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
    delete: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/Songs": {
    get: {
      parameters: {
        query: {
          page?: number;
          size?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Song"][];
          "application/json": components["schemas"]["Song"][];
          "text/json": components["schemas"]["Song"][];
        };
      };
    };
    post: {
      requestBody: {
        "application/json-patch+json": components["schemas"]["Song"];
        "application/json": components["schemas"]["Song"];
        "text/json": components["schemas"]["Song"];
        "application/*+json": components["schemas"]["Song"];
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Song"];
          "application/json": components["schemas"]["Song"];
          "text/json": components["schemas"]["Song"];
        };
      };
    };
  };
  "/Songs/Highlights": {
    get: {
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Song"][];
          "application/json": components["schemas"]["Song"][];
          "text/json": components["schemas"]["Song"][];
        };
      };
    };
  };
  "/Songs/Genre/{option}": {
    get: {
      parameters: {
        path: {
          option: string;
        };
        query: {
          page?: number;
          size?: number;
        };
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Song"][];
          "application/json": components["schemas"]["Song"][];
          "text/json": components["schemas"]["Song"][];
        };
      };
    };
  };
  "/Songs/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["Song"];
          "application/json": components["schemas"]["Song"];
          "text/json": components["schemas"]["Song"];
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: number;
        };
      };
      requestBody: {
        "application/json-patch+json": components["schemas"]["Song"];
        "application/json": components["schemas"]["Song"];
        "text/json": components["schemas"]["Song"];
        "application/*+json": components["schemas"]["Song"];
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
    delete: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
  "/Users": {
    get: {
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["User"][];
          "application/json": components["schemas"]["User"][];
          "text/json": components["schemas"]["User"][];
        };
      };
    };
    post: {
      requestBody: {
        "application/json-patch+json": components["schemas"]["User"];
        "application/json": components["schemas"]["User"];
        "text/json": components["schemas"]["User"];
        "application/*+json": components["schemas"]["User"];
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["User"];
          "application/json": components["schemas"]["User"];
          "text/json": components["schemas"]["User"];
        };
      };
    };
  };
  "/Users/{id}": {
    get: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          "text/plain": components["schemas"]["User"];
          "application/json": components["schemas"]["User"];
          "text/json": components["schemas"]["User"];
        };
      };
    };
    put: {
      parameters: {
        path: {
          id: number;
        };
      };
      requestBody: {
        "application/json-patch+json": components["schemas"]["User"];
        "application/json": components["schemas"]["User"];
        "text/json": components["schemas"]["User"];
        "application/*+json": components["schemas"]["User"];
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
    delete: {
      parameters: {
        path: {
          id: number;
        };
      };
      responses: {
        /** Success */
        200: unknown;
      };
    };
  };
}

export interface operations {}

export interface components {
  schemas: {
    MediaType: 0 | 1 | 2;
    Gallery: {
      id?: number;
      media: components["schemas"]["Media"][];
    };
    Media: {
      created?: string;
      lastModified?: string;
      id?: number;
      url: string;
      type: components["schemas"]["MediaType"];
      isVisible: boolean;
      gallery?: components["schemas"]["Gallery"][] | null;
    };
    Song: {
      created?: string;
      lastModified?: string;
      id?: number;
      album?: components["schemas"]["Album"];
      title: string;
      genre?: string | null;
      isHighlight: boolean;
      soundCloud?: string | null;
      audioId?: number | null;
      audio?: components["schemas"]["Media"];
    };
    Album: {
      created?: string;
      lastModified?: string;
      id?: number;
      title: string;
      genre?: string | null;
      songs?: components["schemas"]["Song"][] | null;
      coverImage?: components["schemas"]["Media"];
    };
    Article: {
      created?: string;
      lastModified?: string;
      id?: number;
      title?: string | null;
      content: string;
      songId?: number | null;
      song?: components["schemas"]["Song"];
    };
    EmailPurpose: 0 | 1;
    SenderType: 0 | 1 | 2;
    User: {
      created?: string;
      lastModified?: string;
      id?: number;
      isOwner: boolean;
      email: string;
      facebook?: string | null;
      instagram?: string | null;
      weixin?: string | null;
    };
    Email: {
      created?: string;
      lastModified?: string;
      id?: number;
      address: string;
      message?: string | null;
      purpose?: components["schemas"]["EmailPurpose"];
      sender?: components["schemas"]["SenderType"];
      isSuccess: boolean;
      userId?: number;
      user?: components["schemas"]["User"];
    };
    Post: {
      created?: string;
      lastModified?: string;
      id?: number;
      title: string;
      content?: string | null;
      link?: string | null;
      galleryId?: number | null;
      gallery?: components["schemas"]["Gallery"];
    };
  };
}
