# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

stages:
- stage: Test
  jobs:
  - job:
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Docker@2
        inputs:
          command: 'build'
          Dockerfile: '$(System.DefaultWorkingDirectory)/APIServer/Dockerfile'
          addPipelineData: false
      - script: |
          CONTAINER=$(docker images -qf "label=unittestlayer=true")
          docker create --name testcontainer $CONTAINER
          docker cp testcontainer:/out/testresults ./testresults
          docker stop testcontainer
          docker rm testcontainer
        displayName: Extract Test Reports
        continueOnError: false
      - task: PublishTestResults@2
        inputs:
          testRunner: VSTest
          testResultsFiles: '**/loggedresults.xml'
          searchFolder: '$(System.DefaultWorkingDirectory)/testresults'
          publishRunAttachments: true
          failTaskOnFailedTests: true
      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: 'cobertura'
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/testresults/coverage/coverage.cobertura.xml'
          reportDirectory: '$(System.DefaultWorkingDirectory)/testresults/coverage/reports'
- stage: Build
  jobs:
  - job:
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Aliyun Registry'
        repository: 'destinesiastudio/patriciopersonal-apiserver'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 'dev'