# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

stages:
- stage: Test
  jobs:
  - job:
    pool:
      vmImage: 'windows-latest'
    steps:
      - task: NuGetCommand@2
        inputs:
          command: 'restore'
          restoreSolution: 'xUnitTest.sln'
          feedsToUse: 'select'
          vstsFeed: 'aafeb507-d25f-4f2f-9ce9-31dfd9e795ae'
      - task: VSTest@2
        inputs:
          testSelector: 'testAssemblies'
          testAssemblyVer2: |
            **\bin\$(BuildConfiguration)\**\*test*.dll
            !**\obj\**
            !**\xunit.runner.visualstudio.testadapter.dll
            !**\xunit.runner.visualstudio.dotnetcore.testadapter.dll
          searchFolder: '$(System.DefaultWorkingDirectory)\APIServer.Tests'
- stage: Build
  jobs:
  - job:
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Aliyun Registry'
        repository: 'destinesiastudio/patriciopersonal-apiserver'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 'dev'