# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

resources:
  containers:
  - container: linux # reusable alias
    image: ubuntu-latest
  - container: windows
    image: windows-latest

jobs:
- job: UnitTesting
  container: windows # reference
  steps:
  - task: VSTest@2
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: |
        **\bin\$(BuildConfiguration)\**\*test*.dll
        !**\obj\**
        !**\xunit.runner.visualstudio.testadapter.dll
        !**\xunit.runner.visualstudio.dotnetcore.testadapter.dll
      searchFolder: '$(System.DefaultWorkingDirectory)\APIServer.Tests'

- job: BuildingImage
  container: linux # reference
  steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'Aliyun Registry'
      repository: 'destinesiastudio/patriciopersonal-apiserver'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: 'dev'