# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

variables:
- name: repo
  value: destinesiastudio/patriciopersonal-apiserver
- name: tag
  value: latest
  
stages:
- stage: Build
  jobs:
  - job:
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        command: 'build'
        Dockerfile: '$(System.DefaultWorkingDirectory)/APIServer/Dockerfile'
        addPipelineData: false
        buildContext: '$(System.DefaultWorkingDirectory)/APIServer'
        arguments: '-t $(repo):$(tag)'
    - script: |
        CONTAINER=$(docker images -qf "label=unittestlayer=true")
        echo $CONTAINER
        docker create --name testcontainer $CONTAINER
        docker cp testcontainer:/out/testresults ./testresults
        docker stop testcontainer
        docker rm testcontainer
        echo $(Build.BuildId)
      displayName: Extract Test Reports
      continueOnError: false
    - task: PublishTestResults@2
      inputs:
        testRunner: VSTest
        testResultsFiles: '**/loggedresults.xml'
        searchFolder: '$(System.DefaultWorkingDirectory)/testresults'
        publishRunAttachments: true
        failTaskOnFailedTests: true
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'cobertura'
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/testresults/**/coverage.cobertura.xml'
        pathToSources: '$(System.DefaultWorkingDirectory)/APIServer'
    - script: |
        docker image save $(repo):$(Build.BuildId) -o $(Pipeline.Workspace)/imagesource.tar
      displayName: Docker Image to Artifact
      continueOnError: false
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/imagesource.tar'
        artifact: 'docker-image'
        publishLocation: 'pipeline'
- stage: Push
  jobs:
  - job:
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'docker-image'
        targetPath: '$(Pipeline.Workspace)'
    - script: |
        echo $(Build.BuildId)
        docker load --input $(Pipeline.Workspace)/imagesource.tar
      displayName: Artifact to Docker Image
      continueOnError: false
    - task: Docker@2
      inputs:
        containerRegistry: 'Aliyun Registry'
        repository: $(repo)
        command: 'push'
        addPipelineData: false
        tags: $(tag)